apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-checker
spec:
  selector:
    matchLabels:
      app: website-checker
  replicas: 3
  template:
    metadata:
      labels:
        app: website-checker
    spec:
      containers:
      - name: website-checker
        image: niki4a/website-checker2.0:latest
        ports:
        - containerPort: 5000